Added correct python shebangs and updated README.md with instructions for Arch Linux'
techknowclub/SongDownloader pull request #20
Opened 2016-10-20 16:35 UTC by flhp

I have added shebangs to the python scripts, as well as updated the requirements for Arch Linux.

2016-10-21 08:17 UTC, rkrp requested changes
[deleted]

2016-10-21 08:23 UTC, rkrp requested changes
Arch installation instruction is incorrect.

2016-10-21 08:23 UTC, rkrp commented on README.md
> +        `pacman -S install qt5-base qt5-webkit base-devel python2-pip xorg-server-xvfb jre8-openjdk`
You have included `install` as one of the packages for installation. `pacman` would throw an error failing to find package `install`.

    error: target not found: install

2016-10-21 11:27 UTC, flhp commented
Not sure how that got in there, sorry.
Removed the 'install'.

2016-10-27 19:31 UTC, sachinkamath commented
@flhp Please clone from the upstream for sending in PR's. Accepting this PR is only going to pollute the history. Also, please send in your PR's from a separate branch. Closing this as this in invalid.

2016-10-27 19:31 UTC, closed without merging